### ISSUE TITLE
Item not selected at purchase view

### ISSUE THREAD

**Issue by ZeroCoolHacker** [jai-singhal/croma#1]
![screenshot from 2018-12-10 23-15-12](https://user-images.githubusercontent.com/18724529/49752207-82f10c80-fcd1-11e8-9e82-217a1fd55c74.png)
I have added one item DISPRINE in the database but it is not detecting the medicine in the purchase view.

**Comment by jai-singhal** [comment]
Hello there,
I appreciate that you have found my work interesting. You will be pleased to know that (read README.md), this application is been created as a personal project for myself. 
This application is not fully dynamic, this means you have to create some essential entries from the Django admin itself. However, I am trying to make the fully dynamic version of this application. 

To rectify this problem, you have to insert the items from Item Master only, If you create the item from Django admin dashboard or from the database, it will not reflect in the list of items in sales/purchase, because I have created the local storage of the items at the client side, which is only reflected when you insert item in the item master only!!

Also, I have added some changes, so please make a pull request, to view the new changes. 

Cheers!!
